Update generate-json

diff --git a/.github/workflows/generate-json.yml b/.github/workflows/generate-json.yml
--- a/.github/workflows/generate-json.yml
+++ b/.github/workflows/generate-json.yml
@@ -23,11 +23,9 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-        continue-on-error: true
 
       - name: Run generate-json.py
         run: python generate-json.py
-        continue-on-error: true
 
       - name: Commit and push if changes
         run: |
@@ -35,11 +33,9 @@ jobs:
           git config --local user.name "GitHub Action"
           git add -A
           git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate JSON files" && git push)
-        continue-on-error: true
 
       - name: Check for errors
+        if: failure()
         run: |
-          if [ ${{ job.status }} == 'failure' ]; then
-            echo "Workflow failed. Check the logs for more information."
-            exit 1
-          fi
+          echo "Workflow failed. Check the logs for more information."
+          exit 1
