Update generate-json.yml

diff --git a/.github/workflows/generate-json.yml b/.github/workflows/generate-json.yml
--- a/.github/workflows/generate-json.yml
+++ b/.github/workflows/generate-json.yml
@@ -12,10 +12,10 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up Python
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v5
         with:
           python-version: '3.x'
 
@@ -23,9 +23,11 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
+        continue-on-error: true
 
       - name: Run generate-json.py
         run: python generate-json.py
+        continue-on-error: true
 
       - name: Commit and push if changes
         run: |
@@ -33,3 +35,11 @@ jobs:
           git config --local user.name "GitHub Action"
           git add -A
           git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate JSON files" && git push)
+        continue-on-error: true
+
+      - name: Check for errors
+        run: |
+          if [ ${{ job.status }} == 'failure' ]; then
+            echo "Workflow failed. Check the logs for more information."
+            exit 1
+          fi
